# Generated by Django 3.1.7 on 2021-03-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Machine')),
                ('mac', models.CharField(max_length=12, unique=True, verbose_name='Mac Address')),
                ('user', models.CharField(max_length=255, verbose_name='System User')),
                ('message', models.TextField(blank=True, null=True)),
                ('client', models.CharField(max_length=255)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Atom'), (2, 'Bhartipay')])),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dt', models.DateField(verbose_name='From Date')),
                ('to_dt', models.DateField(verbose_name='To Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time Added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('soft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.software', verbose_name='Software')),
            ],
        ),
    ]
